version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - ALLOWED_ORIGINS=http://localhost:3000
      - DATABASE_URL=postgresql://drugmatcher:drugmatcher@db:5432/drugmatcher
    depends_on:
      - db
    volumes:
      - ./backend/data:/app/data
      - ./backend/models:/app/models
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=drugmatcher
      - POSTGRES_PASSWORD=drugmatcher
      - POSTGRES_DB=drugmatcher
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

